steps:
  - name: openjdk:17
    id: test
    entrypoint: "/bin/bash"
    args:
      - '-c'
      - |-
        set -x
        ./gradlew check

  - name: openjdk:17
    id: build-image
    entrypoint: "/bin/bash"
    args:
      - '-c'
      - |-
        set -x
        ./gradlew jib --image=us-docker.pkg.dev/$PROJECT_ID/docker-repo/cloud-bigtable-sample:$SHORT_SHA -Djib.to.tags="latest"