apiVersion: v1
kind: Service
metadata:
  name: cloud-bigtable-sample
  labels:
    app: cloud-bigtable-sample
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: cloud-bigtable-sample
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-bigtable-sample-deployment
  labels:
    app: cloud-bigtable-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-bigtable-sample
  template:
    metadata:
      labels:
        app: cloud-bigtable-sample
    spec:
      serviceAccountName: cloud-bigtable-sample-sa
      containers:
        - name: cloud-bigtable-sample
          image: us-docker.pkg.dev/biju-altostrat-demo/docker-repo/cloud-bigtable-sample:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          securityContext:
            runAsUser: 1000
          resources:
            requests:
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080